// Generated by npm run build:plugin. Do not edit directly.

// integrations/hermes/desktop/plugin-entry.ts
import {
  atom,
  Button,
  COMPOSER_AREAS,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  host,
  icons,
  StatusDot,
  Tip,
  cn,
  useValue
} from "@hermes/plugin-sdk";
import * as HermesSdk from "@hermes/plugin-sdk";
import { jsx, jsxs } from "react/jsx-runtime";

// src/one-shot.ts
var OneShotController = class {
  armedTargetId = null;
  generation = 0;
  pending = /* @__PURE__ */ new Map();
  arm(targetId) {
    if (!targetId) throw new Error("one-shot target id is required");
    this.generation += 1;
    this.armedTargetId = targetId;
  }
  disarm() {
    this.generation += 1;
    this.armedTargetId = null;
  }
  current() {
    return this.armedTargetId;
  }
  snapshot(turnId) {
    const existing = this.pending.get(turnId);
    if (existing) return existing;
    if (!this.armedTargetId) return null;
    const snapshot = { targetId: this.armedTargetId, armGeneration: this.generation };
    this.pending.set(turnId, snapshot);
    return snapshot;
  }
  accepted(turnId) {
    const snapshot = this.pending.get(turnId);
    if (!snapshot) return false;
    this.pending.delete(turnId);
    if (snapshot.armGeneration === this.generation && this.armedTargetId === snapshot.targetId) {
      this.armedTargetId = null;
      return true;
    }
    return false;
  }
  rejected(turnId) {
    this.pending.delete(turnId);
  }
};

// src/presets.ts
var codexLunaSolPolicy = {
  version: 1,
  tiers: [
    { id: "fast", label: "Luna \xB7 Medium", provider: "openai-codex", model: "gpt-5.6-luna", reasoningEffort: "medium", minScore: -100 },
    { id: "balanced", label: "Sol \xB7 Medium", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "medium", minScore: 25 },
    { id: "strong", label: "Sol \xB7 High", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "high", minScore: 60 },
    { id: "premium", label: "Sol \xB7 XHigh", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "xhigh", minScore: 90 }
  ],
  signals: [
    {
      id: "explicit-quality",
      reasonCode: "explicit_quality",
      pattern: /(认真|仔细|深入|深度|想清楚|高质量|最好(?:的)?模型|最强|不要敷衍|strict(?:ly)? review|think\s+carefully|high[ -]?quality|best\s+model)/.source,
      weight: 90,
      forceUpgrade: true
    },
    {
      id: "explicit-saving",
      reasonCode: "explicit_saving",
      pattern: /(省额度|节省额度|简单回答|简短回答|不用想太多|低成本|save\s+(?:tokens?|quota)|keep\s+it\s+simple)/.source,
      weight: -45
    },
    {
      id: "high-impact",
      reasonCode: "high_impact",
      pattern: /(删除|覆盖|清空|迁移|批量.*(?:改|写|重命名)|凭据|密码|token|api\s*key|权限|安全|隐私|生产环境|上线|部署|服务器|数据库|备份|恢复|回滚|支付|合同|医疗|药物|delete|overwrite|migrat|credential|permission|security|privacy|production|deploy|database|backup|restore)/.source,
      weight: 45
    },
    {
      id: "complex-reasoning",
      reasonCode: "complex_reasoning",
      pattern: /(架构|系统设计|根因|复盘|取舍|权衡|多约束|长期方案|自动化|路由|批判|本质|交叉验证|architecture|root cause|trade[ -]?off|multi[ -]?constraint|research|cross[ -]?validate)/.source,
      weight: 35
    },
    {
      id: "code-tools",
      reasonCode: "code_or_tools",
      pattern: /(```|\b(?:typescript|javascript|python|react|electron|api|git|sql|docker|regex|json|yaml)\b|代码|源码|报错|测试|构建|编译|终端|命令|文件|网页|搜索)/.source,
      weight: 14
    }
  ],
  simpleRequestPatterns: [
    /^(你好|嗨|hello|hi|谢谢|感谢|好的|好|行|可以|收到|知道了|嗯|哦|翻译[:：]?|润色[:：]?|格式化[:：]?|任务完成了吗|下载好了吗)[？?！!。\s\S]{0,32}$/.source
  ],
  continuationPatterns: [
    /^(你)?(继续|接着|往下|照这个做|按这个来|继续执行|继续吧|开始吧|就这样做)[吧。！!\s]*$/.source,
    /^(continue|keep going|go on|proceed)[.!\s]*$/.source
  ],
  modeBias: { auto: 0, save: -28, quality: 25 },
  attachmentsWeight: 11,
  mediumMessageChars: 180,
  mediumMessageWeight: 16,
  longMessageChars: 600,
  longMessageWeight: 30,
  safetyFloorTierId: "balanced",
  switchUpMargin: 10,
  switchDownMargin: 12,
  contextTokenStep: 4e3,
  maxContextPenalty: 20,
  largeContextStickyTokens: 32e3
};

// src/capabilities.ts
var HERMES_TURN_TARGET_CAPABILITY = "composer.turn-target.v1";
function compatibleTargetIds(capabilities, policy) {
  const policyIds = new Set(policy.tiers.map((target) => target.id));
  return capabilities.targets.filter((target) => target.enabled && !target.requires_approval && policyIds.has(target.id)).map((target) => target.id);
}
var TARGET_ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$/;
var COST_CLASSES = /* @__PURE__ */ new Set(["free", "low", "standard", "premium"]);
function validateHermesCapabilities(value) {
  if (!value || typeof value !== "object") throw new Error("routing capabilities are unavailable");
  if (JSON.stringify(value).length > 65536) throw new Error("routing capability response is too large");
  const data = value;
  if (data.capability !== HERMES_TURN_TARGET_CAPABILITY || data.protocol_version !== 1) {
    throw new Error(`Hermes Gateway does not support ${HERMES_TURN_TARGET_CAPABILITY}`);
  }
  if (!COST_CLASSES.has(String(data.max_cost_class)) || typeof data.allow_cross_provider !== "boolean") {
    throw new Error("Hermes Gateway returned invalid routing policy metadata");
  }
  if (!Array.isArray(data.targets) || data.targets.length === 0 || data.targets.length > 64) {
    throw new Error("Hermes Gateway returned an invalid routing target count");
  }
  const ids = /* @__PURE__ */ new Set();
  for (const target of data.targets) {
    if (!target || typeof target.id !== "string" || !TARGET_ID.test(target.id) || ids.has(target.id) || typeof target.label !== "string" || target.label.length > 128 || !COST_CLASSES.has(String(target.cost_class)) || typeof target.enabled !== "boolean" || typeof target.requires_approval !== "boolean") {
      throw new Error("Hermes Gateway returned invalid routing targets");
    }
    ids.add(target.id);
  }
  return data;
}
var defaultSleep = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
async function requestHermesCapabilities(request, options = {}) {
  const attempts = Math.max(1, Math.min(50, options.attempts ?? 12));
  const delayMs = Math.max(0, Math.min(5e3, options.delayMs ?? 150));
  const sleep = options.sleep ?? defaultSleep;
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return validateHermesCapabilities(await request());
    } catch (error) {
      lastError = error;
      if (attempt < attempts) await sleep(delayMs);
    }
  }
  throw lastError instanceof Error ? lastError : new Error(String(lastError));
}

// src/router.ts
var SAFE_PATTERN_FLAGS = /^[gimsuy]*$/;
function compile(rule) {
  const flags = rule.flags ?? "i";
  if (!SAFE_PATTERN_FLAGS.test(flags)) {
    throw new Error(`Invalid regex flags for signal ${rule.id}`);
  }
  return new RegExp(rule.pattern, flags);
}
function matchesAny(patterns, text) {
  return patterns.some((pattern) => new RegExp(pattern, "i").test(text));
}
function validatePolicy(policy) {
  if (policy.version !== 1) throw new Error("Unsupported policy version");
  if (policy.tiers.length < 2) throw new Error("At least two model tiers are required");
  const ids = /* @__PURE__ */ new Set();
  let previous = Number.NEGATIVE_INFINITY;
  for (const tier of policy.tiers) {
    if (!tier.id || ids.has(tier.id)) throw new Error(`Duplicate or empty tier id: ${tier.id}`);
    if (!tier.provider || !tier.model) throw new Error(`Tier ${tier.id} must declare provider and model`);
    if (tier.minScore < previous) throw new Error("Tiers must be sorted by non-decreasing minScore");
    ids.add(tier.id);
    previous = tier.minScore;
  }
  if (!ids.has(policy.safetyFloorTierId)) throw new Error("safetyFloorTierId must reference a tier");
  for (const rule of policy.signals) compile(rule);
  for (const pattern of [...policy.simpleRequestPatterns, ...policy.continuationPatterns]) {
    new RegExp(pattern, "i");
  }
}
function tierIndex(policy, id) {
  return policy.tiers.findIndex((tier) => tier.id === id);
}
function currentTier(policy, input) {
  const state = input.state;
  if (!state?.currentModel || !state.currentProvider) return void 0;
  return policy.tiers.find(
    (tier) => tier.model === state.currentModel && tier.provider === state.currentProvider && (tier.reasoningEffort ?? "") === (state.currentReasoningEffort ?? "")
  );
}
function availableTiers(input) {
  if (!input.allowedTargetIds) return input.policy.tiers;
  const allowed = new Set(input.allowedTargetIds);
  const tiers = input.policy.tiers.filter((tier) => allowed.has(tier.id));
  if (tiers.length === 0) throw new Error("No allowed routing targets are available");
  return tiers;
}
function chooseTier(tiers, score) {
  let selected = tiers[0];
  for (const tier of tiers) {
    if (score >= tier.minScore) selected = tier;
  }
  return selected;
}
function contextPenalty(policy, tokens) {
  if (!Number.isFinite(tokens) || tokens <= 0) return 0;
  return Math.min(policy.maxContextPenalty, Math.floor(tokens / policy.contextTokenStep));
}
function cacheRisk(tokens, switched) {
  if (!switched) return "none";
  if (tokens >= 32e3) return "high";
  if (tokens >= 8e3) return "medium";
  return "low";
}
function sameTarget(a, b) {
  return Boolean(a && a.provider === b.provider && a.model === b.model && (a.reasoningEffort ?? "") === (b.reasoningEffort ?? ""));
}
function routeMessage(input) {
  validatePolicy(input.policy);
  const text = input.text.trim();
  if (!text || input.mode === "off") return null;
  const policy = input.policy;
  const candidates = availableTiers(input);
  const detectedCurrent = currentTier(policy, input);
  const current = detectedCurrent && candidates.some((tier) => tier.id === detectedCurrent.id) ? detectedCurrent : void 0;
  const estimatedTokens = Math.max(0, input.estimatedContextTokens ?? 0);
  const penalty = contextPenalty(policy, estimatedTokens);
  const findTier = (id) => {
    const tier = policy.tiers.find((item) => item.id === id);
    if (!tier) throw new Error(`Unknown tier: ${id}`);
    if (!candidates.some((item) => item.id === id)) throw new Error(`Routing target is not allowed: ${id}`);
    return tier;
  };
  const finish = (target2, score2, rawTierId, reasons2, hysteresisApplied2 = false) => {
    const switched = Boolean(current) && !sameTarget(current, target2);
    return {
      target: target2,
      score: score2,
      rawTierId,
      reasons: reasons2,
      switched,
      hysteresisApplied: hysteresisApplied2,
      contextPenalty: penalty,
      cacheRisk: cacheRisk(estimatedTokens, switched)
    };
  };
  if (input.oneShotTierId) {
    const target2 = findTier(input.oneShotTierId);
    return finish(target2, Number.POSITIVE_INFINITY, target2.id, ["manual_one_shot"]);
  }
  if (input.mode === "fixed") {
    if (!input.fixedTierId) throw new Error("fixedTierId is required in fixed mode");
    const target2 = findTier(input.fixedTierId);
    return finish(target2, target2.minScore, target2.id, ["fixed_selection"]);
  }
  if (current && matchesAny(policy.continuationPatterns, text)) {
    return finish(current, current.minScore, current.id, ["continuation_sticky"]);
  }
  let score = policy.modeBias[input.mode];
  const reasons = input.mode === "auto" ? [] : [`${input.mode}_mode`];
  let forceUpgrade = false;
  let safetySignal = false;
  for (const rule of policy.signals) {
    if (compile(rule).test(text)) {
      score += rule.weight;
      reasons.push(rule.reasonCode);
      forceUpgrade ||= Boolean(rule.forceUpgrade);
      safetySignal ||= rule.reasonCode === "high_impact";
    }
  }
  if (text.length >= policy.longMessageChars) {
    score += policy.longMessageWeight;
    reasons.push("long_context");
  } else if (text.length >= policy.mediumMessageChars) {
    score += policy.mediumMessageWeight;
    reasons.push("long_context");
  }
  if (input.hasAttachments) {
    score += policy.attachmentsWeight;
    reasons.push("attachments");
  }
  if (matchesAny(policy.simpleRequestPatterns, text)) {
    score -= 35;
    reasons.push("simple_request");
  }
  let raw = chooseTier(candidates, score);
  const floorIndex = tierIndex(policy, policy.safetyFloorTierId);
  if (safetySignal && tierIndex(policy, raw.id) < floorIndex) {
    const safeCandidate = candidates.find((tier) => tierIndex(policy, tier.id) >= floorIndex);
    if (!safeCandidate) throw new Error("No allowed target satisfies the configured safety floor");
    raw = safeCandidate;
    reasons.push("safety_floor");
  }
  if (reasons.length === 0) reasons.push("balanced_default");
  if (input.mode !== "auto") {
    return finish(raw, score, raw.id, reasons);
  }
  if (!current || forceUpgrade || sameTarget(current, raw)) {
    return finish(raw, score, raw.id, reasons);
  }
  const currentIndex = tierIndex(policy, current.id);
  const rawIndex = tierIndex(policy, raw.id);
  let target = raw;
  let hysteresisApplied = false;
  if (rawIndex < currentIndex && estimatedTokens >= (policy.largeContextStickyTokens ?? Number.POSITIVE_INFINITY)) {
    target = current;
    hysteresisApplied = true;
    reasons.push("large_context_sticky");
    return finish(target, score, raw.id, reasons, hysteresisApplied);
  }
  if (rawIndex > currentIndex) {
    const required = raw.minScore + policy.switchUpMargin + penalty;
    if (score < required && !safetySignal) {
      target = current;
      hysteresisApplied = true;
      reasons.push("switch_cost_hold");
    }
  } else if (rawIndex < currentIndex) {
    const downgradeBoundary = current.minScore - policy.switchDownMargin - penalty;
    if (score >= downgradeBoundary) {
      target = current;
      hysteresisApplied = true;
      reasons.push("switch_cost_hold");
    }
  }
  return finish(target, score, raw.id, reasons, hysteresisApplied);
}

// src/safe-route.ts
function routeMessageSafely(input) {
  try {
    return { decision: routeMessage(input), error: null };
  } catch (error) {
    return {
      decision: null,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

// src/router-ui.ts
var ROUTER_CONTROL_MODES = ["auto", "save", "quality", "off"];
var ROUTER_MODE_PRESENTATION = {
  auto: {
    label: "AUTO",
    description: "Choose a target for every new turn.",
    className: "border-primary/35 bg-primary/10 text-primary hover:bg-primary/15"
  },
  save: {
    label: "SAVE",
    description: "Prefer lower-cost targets while keeping safety floors.",
    className: "border-emerald-500/35 bg-emerald-500/10 text-emerald-700 hover:bg-emerald-500/15 dark:text-emerald-300"
  },
  quality: {
    label: "QUALITY",
    description: "Bias each turn toward stronger targets.",
    className: "border-amber-500/40 bg-amber-500/10 text-amber-800 hover:bg-amber-500/15 dark:text-amber-300"
  },
  off: {
    label: "OFF",
    description: "Use Hermes native model selection without routing.",
    className: "border-border/60 bg-muted/25 text-muted-foreground hover:bg-muted/40"
  }
};
function compactTargetLabel(label) {
  const known = {
    "Luna \xB7 Medium": "LUNA M",
    "Sol \xB7 Medium": "SOL M",
    "Sol \xB7 High": "SOL H",
    "Sol \xB7 XHigh": "SOL XH"
  };
  if (known[label]) return known[label];
  const words = [];
  let word = "";
  for (const char of label.slice(0, 256)) {
    if (char === "\xB7" || char.trim() === "") {
      if (word) words.push(word);
      word = "";
    } else {
      word += char;
    }
  }
  if (word) words.push(word);
  const normalized = words.join(" ").toUpperCase();
  return normalized.length > 14 ? `${normalized.slice(0, 13)}\u2026` : normalized;
}
function routerStatusTone(mode, state) {
  if (mode === "off") return "muted";
  if (state === "offline") return "bad";
  if (state === "checking" || state === "routing" || state === "bypass") return "warn";
  return "good";
}
function routerPillText(mode, state, lastTarget) {
  const label = ROUTER_MODE_PRESENTATION[mode].label;
  if (mode === "off") return `${label} \xB7 NATIVE`;
  if (state === "offline") return `${label} \xB7 OFFLINE`;
  if (state === "checking") return `${label} \xB7 CHECKING`;
  if (state === "routing") return `${label} \xB7 ROUTING`;
  if (state === "bypass") return `${label} \xB7 BYPASS`;
  return lastTarget ? `${label} \xB7 ${compactTargetLabel(lastTarget)}` : label;
}

// integrations/hermes/desktop/plugin-entry.ts
var desktopPolicy = typeof __HERMES_TURN_ROUTER_POLICY__ === "undefined" ? codexLunaSolPolicy : __HERMES_TURN_ROUTER_POLICY__;
var PLUGIN_ID = "hermes-turn-router";
var MODE_DOT_CLASS = {
  auto: "bg-primary",
  save: "bg-emerald-500",
  quality: "bg-amber-500",
  off: "bg-muted-foreground/45"
};
var $mode = atom("auto");
var $oneShotArmed = atom(false);
var $availableTargets = atom([]);
var $status = atom("Checking Gateway capability\u2026");
var $lastTarget = atom("");
var $visualState = atom("checking");
var oneShot = new OneShotController();
var capabilityRefresh = null;
function targetLabel(targetId) {
  return desktopPolicy.tiers.find((target) => target.id === targetId)?.label ?? targetId ?? "best target";
}
async function refreshCapabilities(attempts = 12) {
  if (capabilityRefresh) return capabilityRefresh;
  $visualState.set("checking");
  $status.set("Checking Gateway routing capability\u2026");
  const task = (async () => {
    try {
      const response = await requestHermesCapabilities(
        () => host.request("router.capabilities", {}),
        { attempts, delayMs: 150 }
      );
      const compatibleTargets = compatibleTargetIds(response, desktopPolicy);
      $availableTargets.set(compatibleTargets);
      if (host.state.gateway.get() !== "open") {
        $visualState.set("offline");
        $status.set("Gateway offline \xB7 native Hermes send remains available");
      } else if ($mode.get() === "off") {
        $visualState.set("ready");
        $status.set(ROUTER_MODE_PRESENTATION.off.description);
      } else {
        $status.set(`${compatibleTargets.length}/${response.targets.length} targets compatible`);
        $visualState.set(compatibleTargets.length > 0 ? "ready" : "bypass");
      }
      return compatibleTargets.length > 0;
    } catch (error) {
      $availableTargets.set([]);
      if ($mode.get() === "off") {
        $visualState.set("ready");
        $status.set(ROUTER_MODE_PRESENTATION.off.description);
      } else {
        $status.set(error instanceof Error ? error.message : String(error));
        $visualState.set(host.state.gateway.get() === "open" ? "bypass" : "offline");
      }
      return false;
    }
  })();
  capabilityRefresh = task;
  try {
    return await task;
  } finally {
    if (capabilityRefresh === task) capabilityRefresh = null;
  }
}
function setMode(mode) {
  if ($mode.get() === mode) return;
  $mode.set(mode);
  $lastTarget.set("");
  const presentation = ROUTER_MODE_PRESENTATION[mode];
  if (mode === "off") {
    $visualState.set("ready");
    $status.set(presentation.description);
  } else if (host.state.gateway.get() === "open") {
    void refreshCapabilities(4);
  } else {
    $visualState.set("offline");
    $status.set("Gateway offline \xB7 native Hermes send remains available");
  }
  host.notify({
    kind: "info",
    title: `Router \xB7 ${presentation.label}`,
    message: presentation.description
  });
}
function RouterControls() {
  const mode = useValue($mode);
  const oneShotArmed = useValue($oneShotArmed);
  const status = useValue($status);
  const lastTarget = useValue($lastTarget);
  const availableTargets = useValue($availableTargets);
  const gateway = useValue(host.state.gateway);
  const storedVisualState = useValue($visualState);
  const visualState = mode === "off" ? "ready" : storedVisualState;
  const presentation = ROUTER_MODE_PRESENTATION[mode];
  const tone = routerStatusTone(mode, visualState);
  const pillText = routerPillText(mode, visualState, lastTarget);
  const bestTargetId = [...desktopPolicy.tiers].reverse().find((target) => availableTargets.includes(target.id))?.id;
  const stateClass = visualState === "bypass" ? "border-amber-500/45 bg-amber-500/12 text-amber-800 hover:bg-amber-500/18 dark:text-amber-300" : visualState === "offline" ? "border-destructive/45 bg-destructive/10 text-destructive hover:bg-destructive/15" : visualState === "checking" || visualState === "routing" ? "border-amber-500/35 bg-amber-500/8 text-amber-800 hover:bg-amber-500/14 dark:text-amber-300" : presentation.className;
  return jsxs("div", {
    className: "flex items-center gap-1.5",
    children: [
      jsx(DropdownMenu, {
        children: jsxs("div", {
          children: [
            jsx(Tip, {
              label: `${status} \xB7 Click to change routing mode.`,
              side: "top",
              children: jsx(DropdownMenuTrigger, {
                asChild: true,
                children: jsxs(Button, {
                  "aria-label": `Hermes Turn Router: ${pillText}. ${status}`,
                  className: cn(
                    "h-6 gap-1.5 rounded-[4px] px-2 font-semibold tracking-[0.035em] shadow-[inset_0_1px_0_rgba(255,255,255,0.08)]",
                    stateClass
                  ),
                  size: "xs",
                  type: "button",
                  variant: "outline",
                  children: [
                    jsx(StatusDot, {
                      className: cn(
                        MODE_DOT_CLASS[mode],
                        (visualState === "checking" || visualState === "routing") && "animate-pulse"
                      ),
                      tone
                    }),
                    jsx("span", { "aria-live": "polite", children: pillText }),
                    jsx(icons.ChevronDown, { className: "opacity-65" })
                  ]
                })
              })
            }),
            jsx(DropdownMenuContent, {
              align: "end",
              className: "min-w-64",
              side: "top",
              children: ROUTER_CONTROL_MODES.map((value) => {
                const item = ROUTER_MODE_PRESENTATION[value];
                return jsx(DropdownMenuItem, {
                  className: cn("py-2", mode === value && "bg-accent/60"),
                  onSelect: () => setMode(value),
                  children: jsxs("div", {
                    className: "flex min-w-0 items-start gap-2.5",
                    children: [
                      jsx(StatusDot, {
                        className: cn("mt-1.5", MODE_DOT_CLASS[value]),
                        tone: routerStatusTone(value, "ready")
                      }),
                      jsxs("div", {
                        className: "min-w-0",
                        children: [
                          jsxs("div", {
                            className: "flex items-center gap-2 text-xs font-semibold",
                            children: [item.label, mode === value ? "\u2713" : ""]
                          }),
                          jsx("div", {
                            className: "mt-0.5 text-[0.625rem] leading-4 text-muted-foreground",
                            children: item.description
                          })
                        ]
                      })
                    ]
                  })
                }, value);
              })
            })
          ]
        })
      }),
      jsx(Tip, {
        label: oneShotArmed ? `Armed for ${targetLabel(bestTargetId)}. Click to cancel.` : `Use ${targetLabel(bestTargetId)} for the next accepted turn.`,
        side: "top",
        children: jsxs(Button, {
          "aria-label": oneShotArmed ? "Cancel Best once" : "Arm Best once",
          className: cn(
            "h-6 rounded-[4px] px-2 font-semibold tracking-[0.035em]",
            oneShotArmed ? "border-amber-500/45 bg-amber-500/12 text-amber-800 hover:bg-amber-500/18 dark:text-amber-300" : "border-border/55 bg-background/35 text-muted-foreground hover:bg-accent/55 hover:text-foreground"
          ),
          disabled: gateway !== "open" || mode === "off" || !bestTargetId,
          onClick: () => {
            if (!bestTargetId) return;
            if (oneShotArmed) {
              oneShot.disarm();
              $oneShotArmed.set(false);
              host.notify({ kind: "info", title: "Best once cancelled", message: "Automatic routing mode is unchanged." });
            } else {
              oneShot.arm(bestTargetId);
              $oneShotArmed.set(true);
              host.notify({
                kind: "info",
                title: "Best once armed",
                message: `Next accepted turn uses ${targetLabel(bestTargetId)}.`
              });
            }
          },
          size: "xs",
          type: "button",
          variant: "outline",
          children: [
            jsx(StatusDot, {
              className: oneShotArmed ? "animate-pulse bg-amber-500" : "bg-muted-foreground/40",
              tone: oneShotArmed ? "warn" : "muted"
            }),
            oneShotArmed ? "BEST \xB7 ARMED" : "BEST ONCE"
          ]
        })
      })
    ]
  });
}
var plugin = {
  id: PLUGIN_ID,
  name: "Hermes Turn Router",
  description: "Per-turn model routing with cache-aware policies and Gateway-authorized targets.",
  defaultEnabled: true,
  register(ctx) {
    const stored = ctx.storage.get("settings", { mode: "auto" });
    const initialMode = ROUTER_CONTROL_MODES.includes(stored.mode) ? stored.mode : "auto";
    $mode.set(initialMode);
    $lastTarget.set("");
    $visualState.set(initialMode === "off" ? "ready" : "checking");
    $status.set(initialMode === "off" ? ROUTER_MODE_PRESENTATION.off.description : "Checking Gateway routing capability\u2026");
    const save = () => ctx.storage.set("settings", { mode: $mode.get() });
    ctx.onDispose($mode.listen(save));
    const consumeOneShot = (clientTurnId) => {
      if (!oneShot.accepted(clientTurnId)) return;
      $oneShotArmed.set(false);
      $visualState.set("ready");
      const selected = $lastTarget.get() || "best target";
      $status.set(`Best once consumed \xB7 ${selected}`);
      host.notify({ kind: "info", title: "Best once consumed", message: `${selected} accepted this turn.` });
    };
    const acceptedHook = HermesSdk.onTurnAccepted;
    if (typeof acceptedHook === "function") {
      ctx.onDispose(acceptedHook(consumeOneShot));
    } else {
      $status.set("Restart Hermes to activate the per-turn routing SDK");
      $visualState.set("bypass");
    }
    ctx.onDispose(host.onEvent("turn.accepted", (event) => {
      const payload = event.payload;
      if (payload?.client_turn_id) consumeOneShot(payload.client_turn_id);
    }));
    const onGateway = (state) => {
      if (state === "open") {
        if ($mode.get() === "off") {
          $visualState.set("ready");
          $status.set(ROUTER_MODE_PRESENTATION.off.description);
        } else {
          void refreshCapabilities();
        }
      } else {
        $availableTargets.set([]);
        if ($mode.get() !== "off") {
          $visualState.set("offline");
          $status.set("Gateway offline \xB7 native Hermes send remains available");
        }
      }
    };
    ctx.onDispose(host.state.gateway.listen(onGateway));
    onGateway(host.state.gateway.get());
    ctx.registerMany([
      { id: "controls", area: COMPOSER_AREAS.actions, order: 40, render: () => jsx(RouterControls, {}) },
      {
        id: "middleware",
        area: COMPOSER_AREAS.middleware,
        order: 10,
        data: {
          async handler(draft) {
            const mode = $mode.get();
            if (mode === "off") {
              $visualState.set("ready");
              $status.set(ROUTER_MODE_PRESENTATION.off.description);
              return draft;
            }
            const snapshot = oneShot.snapshot(draft.turnEnvelope.clientTurnId);
            let availableTargetIds = $availableTargets.get();
            if (!availableTargetIds.length) {
              await refreshCapabilities(4);
              availableTargetIds = $availableTargets.get();
            }
            if (!availableTargetIds.length) {
              oneShot.rejected(draft.turnEnvelope.clientTurnId);
              $lastTarget.set("bypass");
              $visualState.set("bypass");
              host.notify({ kind: "warning", message: `Router bypassed: ${$status.get()}` });
              return draft;
            }
            const reasoningState = host.state.reasoningEffort;
            $visualState.set("routing");
            $status.set(`${ROUTER_MODE_PRESENTATION[mode].label} \xB7 evaluating this turn\u2026`);
            const routed = routeMessageSafely({
              text: draft.text,
              mode,
              policy: desktopPolicy,
              allowedTargetIds: availableTargetIds,
              ...snapshot ? { oneShotTierId: snapshot.targetId } : {},
              hasAttachments: Boolean(draft.attachments?.length),
              estimatedContextTokens: host.state.focusedUsage.get()?.context_used ?? 0,
              state: {
                currentModel: host.state.model.get(),
                currentProvider: host.state.provider.get(),
                currentReasoningEffort: reasoningState?.get?.()
              }
            });
            if (routed.error) {
              oneShot.rejected(draft.turnEnvelope.clientTurnId);
              if (snapshot) {
                oneShot.disarm();
                $oneShotArmed.set(false);
              }
              $lastTarget.set("bypass");
              $visualState.set("bypass");
              $status.set(`Policy mismatch: ${routed.error}`);
              host.notify({ kind: "warning", message: `Router bypassed: ${routed.error}` });
              return draft;
            }
            const decision = routed.decision;
            if (!decision) {
              $lastTarget.set("");
              $visualState.set("ready");
              $status.set("No routing decision \xB7 native Hermes send");
              return draft;
            }
            $lastTarget.set(decision.target.label);
            $visualState.set("ready");
            $status.set(`${decision.target.label} \xB7 ${decision.reasons.join(", ")}`);
            return {
              ...draft,
              turnEnvelope: {
                ...draft.turnEnvelope,
                routingIntent: {
                  targetId: decision.target.id,
                  mode,
                  reasonCodes: [...decision.reasons]
                }
              }
            };
          }
        }
      }
    ]);
  }
};
var plugin_entry_default = plugin;
export {
  plugin_entry_default as default
};
