// Generated by npm run build:plugin. Do not edit directly.

// integrations/hermes/desktop/plugin-entry.ts
import {
  atom,
  Button,
  COMPOSER_AREAS,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  host,
  icons,
  useValue
} from "@hermes/plugin-sdk";
import * as HermesSdk from "@hermes/plugin-sdk";
import { jsx, jsxs } from "react/jsx-runtime";

// src/one-shot.ts
var OneShotController = class {
  armedTargetId = null;
  generation = 0;
  pending = /* @__PURE__ */ new Map();
  arm(targetId) {
    if (!targetId) throw new Error("one-shot target id is required");
    this.generation += 1;
    this.armedTargetId = targetId;
  }
  disarm() {
    this.generation += 1;
    this.armedTargetId = null;
  }
  current() {
    return this.armedTargetId;
  }
  snapshot(turnId) {
    const existing = this.pending.get(turnId);
    if (existing) return existing;
    if (!this.armedTargetId) return null;
    const snapshot = { targetId: this.armedTargetId, armGeneration: this.generation };
    this.pending.set(turnId, snapshot);
    return snapshot;
  }
  accepted(turnId) {
    const snapshot = this.pending.get(turnId);
    if (!snapshot) return false;
    this.pending.delete(turnId);
    if (snapshot.armGeneration === this.generation && this.armedTargetId === snapshot.targetId) {
      this.armedTargetId = null;
      return true;
    }
    return false;
  }
  rejected(turnId) {
    this.pending.delete(turnId);
  }
};

// src/presets.ts
var codexLunaSolPolicy = {
  version: 1,
  tiers: [
    { id: "fast", label: "Luna \xB7 Medium", provider: "openai-codex", model: "gpt-5.6-luna", reasoningEffort: "medium", minScore: -100 },
    { id: "balanced", label: "Sol \xB7 Medium", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "medium", minScore: 25 },
    { id: "premium", label: "Sol \xB7 XHigh", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "xhigh", minScore: 75 }
  ],
  signals: [
    {
      id: "explicit-quality",
      reasonCode: "explicit_quality",
      pattern: "(\u8BA4\u771F|\u4ED4\u7EC6|\u6DF1\u5165|\u6DF1\u5EA6|\u60F3\u6E05\u695A|\u9AD8\u8D28\u91CF|\u6700\u597D(?:\u7684)?\u6A21\u578B|\u6700\u5F3A|\u4E0D\u8981\u6577\u884D|strict(?:ly)? review|thinks+carefully|high[ -]?quality|bests+model)",
      weight: 90,
      forceUpgrade: true
    },
    {
      id: "explicit-saving",
      reasonCode: "explicit_saving",
      pattern: "(\u7701\u989D\u5EA6|\u8282\u7701\u989D\u5EA6|\u7B80\u5355\u56DE\u7B54|\u7B80\u77ED\u56DE\u7B54|\u4E0D\u7528\u60F3\u592A\u591A|\u4F4E\u6210\u672C|saves+(?:tokens?|quota)|keeps+its+simple)",
      weight: -45
    },
    {
      id: "high-impact",
      reasonCode: "high_impact",
      pattern: "(\u5220\u9664|\u8986\u76D6|\u6E05\u7A7A|\u8FC1\u79FB|\u6279\u91CF.*(?:\u6539|\u5199|\u91CD\u547D\u540D)|\u51ED\u636E|\u5BC6\u7801|token|apis*key|\u6743\u9650|\u5B89\u5168|\u9690\u79C1|\u751F\u4EA7\u73AF\u5883|\u4E0A\u7EBF|\u90E8\u7F72|\u670D\u52A1\u5668|\u6570\u636E\u5E93|\u5907\u4EFD|\u6062\u590D|\u56DE\u6EDA|\u652F\u4ED8|\u5408\u540C|\u533B\u7597|\u836F\u7269|delete|overwrite|migrat|credential|permission|security|privacy|production|deploy|database|backup|restore)",
      weight: 45
    },
    {
      id: "complex-reasoning",
      reasonCode: "complex_reasoning",
      pattern: "(\u67B6\u6784|\u7CFB\u7EDF\u8BBE\u8BA1|\u6839\u56E0|\u590D\u76D8|\u53D6\u820D|\u6743\u8861|\u591A\u7EA6\u675F|\u957F\u671F\u65B9\u6848|\u81EA\u52A8\u5316|\u8DEF\u7531|\u6279\u5224|\u672C\u8D28|\u4EA4\u53C9\u9A8C\u8BC1|architecture|root cause|trade[ -]?off|multi[ -]?constraint|research|cross[ -]?validate)",
      weight: 35
    },
    {
      id: "code-tools",
      reasonCode: "code_or_tools",
      pattern: "(```|\b(?:typescript|javascript|python|react|electron|api|git|sql|docker|regex|json|yaml)\b|\u4EE3\u7801|\u6E90\u7801|\u62A5\u9519|\u6D4B\u8BD5|\u6784\u5EFA|\u7F16\u8BD1|\u7EC8\u7AEF|\u547D\u4EE4|\u6587\u4EF6|\u7F51\u9875|\u641C\u7D22)",
      weight: 14
    }
  ],
  simpleRequestPatterns: [
    "^(\u4F60\u597D|\u55E8|hello|hi|\u8C22\u8C22|\u611F\u8C22|\u597D\u7684|\u597D|\u884C|\u53EF\u4EE5|\u6536\u5230|\u77E5\u9053\u4E86|\u55EF|\u54E6|\u7FFB\u8BD1[:\uFF1A]?|\u6DA6\u8272[:\uFF1A]?|\u683C\u5F0F\u5316[:\uFF1A]?|\u4EFB\u52A1\u5B8C\u6210\u4E86\u5417|\u4E0B\u8F7D\u597D\u4E86\u5417)[\uFF1F?\uFF01!\u3002sS]{0,32}$"
  ],
  continuationPatterns: [
    "^(\u4F60)?(\u7EE7\u7EED|\u63A5\u7740|\u5F80\u4E0B|\u7167\u8FD9\u4E2A\u505A|\u6309\u8FD9\u4E2A\u6765|\u7EE7\u7EED\u6267\u884C|\u7EE7\u7EED\u5427|\u5F00\u59CB\u5427|\u5C31\u8FD9\u6837\u505A)[\u5427\u3002\uFF01!s]*$",
    "^(continue|keep going|go on|proceed)[.!s]*$"
  ],
  modeBias: { auto: 0, save: -28, quality: 25 },
  attachmentsWeight: 10,
  mediumMessageChars: 180,
  mediumMessageWeight: 16,
  longMessageChars: 600,
  longMessageWeight: 30,
  safetyFloorTierId: "balanced",
  switchUpMargin: 10,
  switchDownMargin: 12,
  contextTokenStep: 4e3,
  maxContextPenalty: 20
};

// src/router.ts
var SAFE_PATTERN_FLAGS = /^[gimsuy]*$/;
function compile(rule) {
  const flags = rule.flags ?? "i";
  if (!SAFE_PATTERN_FLAGS.test(flags)) {
    throw new Error(`Invalid regex flags for signal ${rule.id}`);
  }
  return new RegExp(rule.pattern, flags);
}
function matchesAny(patterns, text) {
  return patterns.some((pattern) => new RegExp(pattern, "i").test(text));
}
function validatePolicy(policy) {
  if (policy.version !== 1) throw new Error("Unsupported policy version");
  if (policy.tiers.length < 2) throw new Error("At least two model tiers are required");
  const ids = /* @__PURE__ */ new Set();
  let previous = Number.NEGATIVE_INFINITY;
  for (const tier of policy.tiers) {
    if (!tier.id || ids.has(tier.id)) throw new Error(`Duplicate or empty tier id: ${tier.id}`);
    if (!tier.provider || !tier.model) throw new Error(`Tier ${tier.id} must declare provider and model`);
    if (tier.minScore < previous) throw new Error("Tiers must be sorted by non-decreasing minScore");
    ids.add(tier.id);
    previous = tier.minScore;
  }
  if (!ids.has(policy.safetyFloorTierId)) throw new Error("safetyFloorTierId must reference a tier");
  for (const rule of policy.signals) compile(rule);
  for (const pattern of [...policy.simpleRequestPatterns, ...policy.continuationPatterns]) {
    new RegExp(pattern, "i");
  }
}
function tierIndex(policy, id) {
  return policy.tiers.findIndex((tier) => tier.id === id);
}
function currentTier(policy, input) {
  const state = input.state;
  if (!state?.currentModel || !state.currentProvider) return void 0;
  return policy.tiers.find(
    (tier) => tier.model === state.currentModel && tier.provider === state.currentProvider && (tier.reasoningEffort ?? "") === (state.currentReasoningEffort ?? "")
  );
}
function availableTiers(input) {
  if (!input.allowedTargetIds) return input.policy.tiers;
  const allowed = new Set(input.allowedTargetIds);
  const tiers = input.policy.tiers.filter((tier) => allowed.has(tier.id));
  if (tiers.length === 0) throw new Error("No allowed routing targets are available");
  return tiers;
}
function chooseTier(tiers, score) {
  let selected = tiers[0];
  for (const tier of tiers) {
    if (score >= tier.minScore) selected = tier;
  }
  return selected;
}
function contextPenalty(policy, tokens) {
  if (!Number.isFinite(tokens) || tokens <= 0) return 0;
  return Math.min(policy.maxContextPenalty, Math.floor(tokens / policy.contextTokenStep));
}
function cacheRisk(tokens, switched) {
  if (!switched) return "none";
  if (tokens >= 32e3) return "high";
  if (tokens >= 8e3) return "medium";
  return "low";
}
function sameTarget(a, b) {
  return Boolean(a && a.provider === b.provider && a.model === b.model && (a.reasoningEffort ?? "") === (b.reasoningEffort ?? ""));
}
function routeMessage(input) {
  validatePolicy(input.policy);
  const text = input.text.trim();
  if (!text || input.mode === "off") return null;
  const policy = input.policy;
  const candidates = availableTiers(input);
  const detectedCurrent = currentTier(policy, input);
  const current = detectedCurrent && candidates.some((tier) => tier.id === detectedCurrent.id) ? detectedCurrent : void 0;
  const estimatedTokens = Math.max(0, input.estimatedContextTokens ?? 0);
  const penalty = contextPenalty(policy, estimatedTokens);
  const findTier = (id) => {
    const tier = policy.tiers.find((item) => item.id === id);
    if (!tier) throw new Error(`Unknown tier: ${id}`);
    if (!candidates.some((item) => item.id === id)) throw new Error(`Routing target is not allowed: ${id}`);
    return tier;
  };
  const finish = (target2, score2, rawTierId, reasons2, hysteresisApplied2 = false) => {
    const switched = Boolean(current) && !sameTarget(current, target2);
    return {
      target: target2,
      score: score2,
      rawTierId,
      reasons: reasons2,
      switched,
      hysteresisApplied: hysteresisApplied2,
      contextPenalty: penalty,
      cacheRisk: cacheRisk(estimatedTokens, switched)
    };
  };
  if (input.oneShotTierId) {
    const target2 = findTier(input.oneShotTierId);
    return finish(target2, Number.POSITIVE_INFINITY, target2.id, ["manual_one_shot"]);
  }
  if (input.mode === "fixed") {
    if (!input.fixedTierId) throw new Error("fixedTierId is required in fixed mode");
    const target2 = findTier(input.fixedTierId);
    return finish(target2, target2.minScore, target2.id, ["fixed_selection"]);
  }
  if (current && matchesAny(policy.continuationPatterns, text)) {
    return finish(current, current.minScore, current.id, ["continuation_sticky"]);
  }
  let score = policy.modeBias[input.mode];
  const reasons = input.mode === "auto" ? [] : [`${input.mode}_mode`];
  let forceUpgrade = false;
  let safetySignal = false;
  for (const rule of policy.signals) {
    if (compile(rule).test(text)) {
      score += rule.weight;
      reasons.push(rule.reasonCode);
      forceUpgrade ||= Boolean(rule.forceUpgrade);
      safetySignal ||= rule.reasonCode === "high_impact";
    }
  }
  if (text.length >= policy.longMessageChars) {
    score += policy.longMessageWeight;
    reasons.push("long_context");
  } else if (text.length >= policy.mediumMessageChars) {
    score += policy.mediumMessageWeight;
    reasons.push("long_context");
  }
  if (input.hasAttachments) {
    score += policy.attachmentsWeight;
    reasons.push("attachments");
  }
  if (matchesAny(policy.simpleRequestPatterns, text)) {
    score -= 35;
    reasons.push("simple_request");
  }
  let raw = chooseTier(candidates, score);
  const floorIndex = tierIndex(policy, policy.safetyFloorTierId);
  if (safetySignal && tierIndex(policy, raw.id) < floorIndex) {
    const safeCandidate = candidates.find((tier) => tierIndex(policy, tier.id) >= floorIndex);
    if (!safeCandidate) throw new Error("No allowed target satisfies the configured safety floor");
    raw = safeCandidate;
    reasons.push("safety_floor");
  }
  if (reasons.length === 0) reasons.push("balanced_default");
  if (!current || forceUpgrade || sameTarget(current, raw)) {
    return finish(raw, score, raw.id, reasons);
  }
  const currentIndex = tierIndex(policy, current.id);
  const rawIndex = tierIndex(policy, raw.id);
  let target = raw;
  let hysteresisApplied = false;
  if (rawIndex > currentIndex) {
    const required = raw.minScore + policy.switchUpMargin + penalty;
    if (score < required && !safetySignal) {
      target = current;
      hysteresisApplied = true;
      reasons.push("switch_cost_hold");
    }
  } else if (rawIndex < currentIndex) {
    const downgradeBoundary = current.minScore - policy.switchDownMargin - penalty;
    if (score >= downgradeBoundary) {
      target = current;
      hysteresisApplied = true;
      reasons.push("switch_cost_hold");
    }
  }
  return finish(target, score, raw.id, reasons, hysteresisApplied);
}

// src/capabilities.ts
var HERMES_TURN_TARGET_CAPABILITY = "composer.turn-target.v1";
var TARGET_ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$/;
var COST_CLASSES = /* @__PURE__ */ new Set(["free", "low", "standard", "premium"]);
function validateHermesCapabilities(value) {
  if (!value || typeof value !== "object") throw new Error("routing capabilities are unavailable");
  if (JSON.stringify(value).length > 65536) throw new Error("routing capability response is too large");
  const data = value;
  if (data.capability !== HERMES_TURN_TARGET_CAPABILITY || data.protocol_version !== 1) {
    throw new Error(`Hermes Gateway does not support ${HERMES_TURN_TARGET_CAPABILITY}`);
  }
  if (!COST_CLASSES.has(String(data.max_cost_class)) || typeof data.allow_cross_provider !== "boolean") {
    throw new Error("Hermes Gateway returned invalid routing policy metadata");
  }
  if (!Array.isArray(data.targets) || data.targets.length === 0 || data.targets.length > 64) {
    throw new Error("Hermes Gateway returned an invalid routing target count");
  }
  const ids = /* @__PURE__ */ new Set();
  for (const target of data.targets) {
    if (!target || typeof target.id !== "string" || !TARGET_ID.test(target.id) || ids.has(target.id) || typeof target.label !== "string" || target.label.length > 128 || !COST_CLASSES.has(String(target.cost_class)) || typeof target.enabled !== "boolean" || typeof target.requires_approval !== "boolean") {
      throw new Error("Hermes Gateway returned invalid routing targets");
    }
    ids.add(target.id);
  }
  return data;
}

// integrations/hermes/desktop/plugin-entry.ts
var PLUGIN_ID = "hermes-turn-router";
var MODES = ["auto", "save", "quality", "fixed", "off"];
var $mode = atom("auto");
var $fixedTarget = atom("balanced");
var $oneShotArmed = atom(false);
var $availableTargets = atom([]);
var $status = atom("Checking Gateway capability\u2026");
var oneShot = new OneShotController();
async function refreshCapabilities() {
  try {
    const response = validateHermesCapabilities(await host.request("router.capabilities", {}));
    $availableTargets.set(
      response.targets.filter((target) => target.enabled && !target.requires_approval).map((target) => target.id)
    );
    $status.set(`${response.targets.length} targets available`);
  } catch (error) {
    $availableTargets.set([]);
    $status.set(error instanceof Error ? error.message : String(error));
  }
}
function setMode(mode) {
  $mode.set(mode);
}
function RouterControls() {
  const mode = useValue($mode);
  const oneShotArmed = useValue($oneShotArmed);
  const status = useValue($status);
  const gateway = useValue(host.state.gateway);
  return jsxs("div", {
    className: "flex items-center gap-1",
    title: status,
    children: [
      jsx(DropdownMenu, {
        children: jsxs("div", {
          children: [
            jsx(DropdownMenuTrigger, {
              asChild: true,
              children: jsxs(Button, {
                "aria-label": "Hermes Turn Router mode",
                disabled: gateway !== "open",
                size: "xs",
                type: "button",
                variant: "ghost",
                children: [jsx(icons.Brain, {}), `Router \xB7 ${mode}`, jsx(icons.ChevronDown, {})]
              })
            }),
            jsx(DropdownMenuContent, {
              align: "end",
              side: "top",
              children: MODES.map((value) => jsx(DropdownMenuItem, {
                onSelect: () => setMode(value),
                children: `${mode === value ? "\u2713 " : ""}${value}`
              }, value))
            })
          ]
        })
      }),
      jsx(Button, {
        disabled: gateway !== "open",
        onClick: () => {
          if (oneShotArmed) {
            oneShot.disarm();
            $oneShotArmed.set(false);
          } else {
            oneShot.arm("premium");
            $oneShotArmed.set(true);
          }
        },
        size: "xs",
        type: "button",
        variant: oneShotArmed ? "secondary" : "ghost",
        children: oneShotArmed ? "Best \u2713" : "Best once"
      })
    ]
  });
}
var plugin = {
  id: PLUGIN_ID,
  name: "Hermes Turn Router",
  description: "Per-turn model routing with cache-aware policies and Gateway-authorized targets.",
  defaultEnabled: true,
  register(ctx) {
    const stored = ctx.storage.get("settings", { fixedTarget: "balanced", mode: "auto" });
    $mode.set(MODES.includes(stored.mode) ? stored.mode : "auto");
    $fixedTarget.set(typeof stored.fixedTarget === "string" ? stored.fixedTarget : "balanced");
    const save = () => ctx.storage.set("settings", { fixedTarget: $fixedTarget.get(), mode: $mode.get() });
    ctx.onDispose($mode.listen(save));
    ctx.onDispose($fixedTarget.listen(save));
    const acceptedHook = HermesSdk.onTurnAccepted;
    if (typeof acceptedHook === "function") {
      ctx.onDispose(acceptedHook((clientTurnId) => {
        if (oneShot.accepted(clientTurnId)) $oneShotArmed.set(false);
      }));
    } else {
      $status.set("Restart Hermes to activate the per-turn routing SDK");
    }
    ctx.onDispose(host.onEvent("turn.accepted", (event) => {
      const payload = event.payload;
      if (payload?.client_turn_id && oneShot.accepted(payload.client_turn_id)) {
        $oneShotArmed.set(false);
      }
    }));
    const onGateway = (state) => {
      if (state === "open") void refreshCapabilities();
    };
    ctx.onDispose(host.state.gateway.listen(onGateway));
    onGateway(host.state.gateway.get());
    ctx.registerMany([
      { id: "controls", area: COMPOSER_AREAS.actions, order: 40, render: () => jsx(RouterControls, {}) },
      {
        id: "middleware",
        area: COMPOSER_AREAS.middleware,
        order: 10,
        data: {
          handler(draft) {
            const mode = $mode.get();
            if (mode === "off") return draft;
            const snapshot = oneShot.snapshot(draft.turnEnvelope.clientTurnId);
            const availableTargetIds = $availableTargets.get();
            if (!availableTargetIds.length) {
              oneShot.rejected(draft.turnEnvelope.clientTurnId);
              host.notify({ kind: "error", message: $status.get() });
              return null;
            }
            const decision = routeMessage({
              text: draft.text,
              mode,
              policy: codexLunaSolPolicy,
              allowedTargetIds: availableTargetIds,
              ...mode === "fixed" ? { fixedTierId: $fixedTarget.get() } : {},
              ...snapshot ? { oneShotTierId: snapshot.targetId } : {},
              hasAttachments: Boolean(draft.attachments?.length),
              estimatedContextTokens: host.state.focusedUsage.get()?.context_used ?? 0,
              state: {
                currentModel: host.state.model.get(),
                currentProvider: host.state.provider.get()
              }
            });
            if (!decision) return draft;
            return {
              ...draft,
              turnEnvelope: {
                ...draft.turnEnvelope,
                routingIntent: {
                  targetId: decision.target.id,
                  mode,
                  reasonCodes: [...decision.reasons]
                }
              }
            };
          }
        }
      }
    ]);
  }
};
var plugin_entry_default = plugin;
export {
  plugin_entry_default as default
};
