// Generated by npm run build:plugin. Do not edit directly.

// integrations/hermes/desktop/plugin-entry.ts
import {
  atom,
  Button,
  COMPOSER_AREAS,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  host,
  icons,
  useValue
} from "@hermes/plugin-sdk";
import * as HermesSdk from "@hermes/plugin-sdk";
import { jsx, jsxs } from "react/jsx-runtime";

// src/one-shot.ts
var OneShotController = class {
  armedTargetId = null;
  generation = 0;
  pending = /* @__PURE__ */ new Map();
  arm(targetId) {
    if (!targetId) throw new Error("one-shot target id is required");
    this.generation += 1;
    this.armedTargetId = targetId;
  }
  disarm() {
    this.generation += 1;
    this.armedTargetId = null;
  }
  current() {
    return this.armedTargetId;
  }
  snapshot(turnId) {
    const existing = this.pending.get(turnId);
    if (existing) return existing;
    if (!this.armedTargetId) return null;
    const snapshot = { targetId: this.armedTargetId, armGeneration: this.generation };
    this.pending.set(turnId, snapshot);
    return snapshot;
  }
  accepted(turnId) {
    const snapshot = this.pending.get(turnId);
    if (!snapshot) return false;
    this.pending.delete(turnId);
    if (snapshot.armGeneration === this.generation && this.armedTargetId === snapshot.targetId) {
      this.armedTargetId = null;
      return true;
    }
    return false;
  }
  rejected(turnId) {
    this.pending.delete(turnId);
  }
};

// src/presets.ts
var codexLunaSolPolicy = {
  version: 1,
  tiers: [
    { id: "fast", label: "Luna \xB7 Medium", provider: "openai-codex", model: "gpt-5.6-luna", reasoningEffort: "medium", minScore: -100 },
    { id: "balanced", label: "Sol \xB7 Medium", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "medium", minScore: 25 },
    { id: "strong", label: "Sol \xB7 High", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "high", minScore: 60 },
    { id: "premium", label: "Sol \xB7 XHigh", provider: "openai-codex", model: "gpt-5.6-sol", reasoningEffort: "xhigh", minScore: 90 }
  ],
  signals: [
    {
      id: "explicit-quality",
      reasonCode: "explicit_quality",
      pattern: /(认真|仔细|深入|深度|想清楚|高质量|最好(?:的)?模型|最强|不要敷衍|strict(?:ly)? review|think\s+carefully|high[ -]?quality|best\s+model)/.source,
      weight: 90,
      forceUpgrade: true
    },
    {
      id: "explicit-saving",
      reasonCode: "explicit_saving",
      pattern: /(省额度|节省额度|简单回答|简短回答|不用想太多|低成本|save\s+(?:tokens?|quota)|keep\s+it\s+simple)/.source,
      weight: -45
    },
    {
      id: "high-impact",
      reasonCode: "high_impact",
      pattern: /(删除|覆盖|清空|迁移|批量.*(?:改|写|重命名)|凭据|密码|token|api\s*key|权限|安全|隐私|生产环境|上线|部署|服务器|数据库|备份|恢复|回滚|支付|合同|医疗|药物|delete|overwrite|migrat|credential|permission|security|privacy|production|deploy|database|backup|restore)/.source,
      weight: 45
    },
    {
      id: "complex-reasoning",
      reasonCode: "complex_reasoning",
      pattern: /(架构|系统设计|根因|复盘|取舍|权衡|多约束|长期方案|自动化|路由|批判|本质|交叉验证|architecture|root cause|trade[ -]?off|multi[ -]?constraint|research|cross[ -]?validate)/.source,
      weight: 35
    },
    {
      id: "code-tools",
      reasonCode: "code_or_tools",
      pattern: /(```|\b(?:typescript|javascript|python|react|electron|api|git|sql|docker|regex|json|yaml)\b|代码|源码|报错|测试|构建|编译|终端|命令|文件|网页|搜索)/.source,
      weight: 14
    }
  ],
  simpleRequestPatterns: [
    /^(你好|嗨|hello|hi|谢谢|感谢|好的|好|行|可以|收到|知道了|嗯|哦|翻译[:：]?|润色[:：]?|格式化[:：]?|任务完成了吗|下载好了吗)[？?！!。\s\S]{0,32}$/.source
  ],
  continuationPatterns: [
    /^(你)?(继续|接着|往下|照这个做|按这个来|继续执行|继续吧|开始吧|就这样做)[吧。！!\s]*$/.source,
    /^(continue|keep going|go on|proceed)[.!\s]*$/.source
  ],
  modeBias: { auto: 0, save: -28, quality: 25 },
  attachmentsWeight: 11,
  mediumMessageChars: 180,
  mediumMessageWeight: 16,
  longMessageChars: 600,
  longMessageWeight: 30,
  safetyFloorTierId: "balanced",
  switchUpMargin: 10,
  switchDownMargin: 12,
  contextTokenStep: 4e3,
  maxContextPenalty: 20,
  largeContextStickyTokens: 32e3
};

// src/router.ts
var SAFE_PATTERN_FLAGS = /^[gimsuy]*$/;
function compile(rule) {
  const flags = rule.flags ?? "i";
  if (!SAFE_PATTERN_FLAGS.test(flags)) {
    throw new Error(`Invalid regex flags for signal ${rule.id}`);
  }
  return new RegExp(rule.pattern, flags);
}
function matchesAny(patterns, text) {
  return patterns.some((pattern) => new RegExp(pattern, "i").test(text));
}
function validatePolicy(policy) {
  if (policy.version !== 1) throw new Error("Unsupported policy version");
  if (policy.tiers.length < 2) throw new Error("At least two model tiers are required");
  const ids = /* @__PURE__ */ new Set();
  let previous = Number.NEGATIVE_INFINITY;
  for (const tier of policy.tiers) {
    if (!tier.id || ids.has(tier.id)) throw new Error(`Duplicate or empty tier id: ${tier.id}`);
    if (!tier.provider || !tier.model) throw new Error(`Tier ${tier.id} must declare provider and model`);
    if (tier.minScore < previous) throw new Error("Tiers must be sorted by non-decreasing minScore");
    ids.add(tier.id);
    previous = tier.minScore;
  }
  if (!ids.has(policy.safetyFloorTierId)) throw new Error("safetyFloorTierId must reference a tier");
  for (const rule of policy.signals) compile(rule);
  for (const pattern of [...policy.simpleRequestPatterns, ...policy.continuationPatterns]) {
    new RegExp(pattern, "i");
  }
}
function tierIndex(policy, id) {
  return policy.tiers.findIndex((tier) => tier.id === id);
}
function currentTier(policy, input) {
  const state = input.state;
  if (!state?.currentModel || !state.currentProvider) return void 0;
  return policy.tiers.find(
    (tier) => tier.model === state.currentModel && tier.provider === state.currentProvider && (tier.reasoningEffort ?? "") === (state.currentReasoningEffort ?? "")
  );
}
function availableTiers(input) {
  if (!input.allowedTargetIds) return input.policy.tiers;
  const allowed = new Set(input.allowedTargetIds);
  const tiers = input.policy.tiers.filter((tier) => allowed.has(tier.id));
  if (tiers.length === 0) throw new Error("No allowed routing targets are available");
  return tiers;
}
function chooseTier(tiers, score) {
  let selected = tiers[0];
  for (const tier of tiers) {
    if (score >= tier.minScore) selected = tier;
  }
  return selected;
}
function contextPenalty(policy, tokens) {
  if (!Number.isFinite(tokens) || tokens <= 0) return 0;
  return Math.min(policy.maxContextPenalty, Math.floor(tokens / policy.contextTokenStep));
}
function cacheRisk(tokens, switched) {
  if (!switched) return "none";
  if (tokens >= 32e3) return "high";
  if (tokens >= 8e3) return "medium";
  return "low";
}
function sameTarget(a, b) {
  return Boolean(a && a.provider === b.provider && a.model === b.model && (a.reasoningEffort ?? "") === (b.reasoningEffort ?? ""));
}
function routeMessage(input) {
  validatePolicy(input.policy);
  const text = input.text.trim();
  if (!text || input.mode === "off") return null;
  const policy = input.policy;
  const candidates = availableTiers(input);
  const detectedCurrent = currentTier(policy, input);
  const current = detectedCurrent && candidates.some((tier) => tier.id === detectedCurrent.id) ? detectedCurrent : void 0;
  const estimatedTokens = Math.max(0, input.estimatedContextTokens ?? 0);
  const penalty = contextPenalty(policy, estimatedTokens);
  const findTier = (id) => {
    const tier = policy.tiers.find((item) => item.id === id);
    if (!tier) throw new Error(`Unknown tier: ${id}`);
    if (!candidates.some((item) => item.id === id)) throw new Error(`Routing target is not allowed: ${id}`);
    return tier;
  };
  const finish = (target2, score2, rawTierId, reasons2, hysteresisApplied2 = false) => {
    const switched = Boolean(current) && !sameTarget(current, target2);
    return {
      target: target2,
      score: score2,
      rawTierId,
      reasons: reasons2,
      switched,
      hysteresisApplied: hysteresisApplied2,
      contextPenalty: penalty,
      cacheRisk: cacheRisk(estimatedTokens, switched)
    };
  };
  if (input.oneShotTierId) {
    const target2 = findTier(input.oneShotTierId);
    return finish(target2, Number.POSITIVE_INFINITY, target2.id, ["manual_one_shot"]);
  }
  if (input.mode === "fixed") {
    if (!input.fixedTierId) throw new Error("fixedTierId is required in fixed mode");
    const target2 = findTier(input.fixedTierId);
    return finish(target2, target2.minScore, target2.id, ["fixed_selection"]);
  }
  if (current && matchesAny(policy.continuationPatterns, text)) {
    return finish(current, current.minScore, current.id, ["continuation_sticky"]);
  }
  let score = policy.modeBias[input.mode];
  const reasons = input.mode === "auto" ? [] : [`${input.mode}_mode`];
  let forceUpgrade = false;
  let safetySignal = false;
  for (const rule of policy.signals) {
    if (compile(rule).test(text)) {
      score += rule.weight;
      reasons.push(rule.reasonCode);
      forceUpgrade ||= Boolean(rule.forceUpgrade);
      safetySignal ||= rule.reasonCode === "high_impact";
    }
  }
  if (text.length >= policy.longMessageChars) {
    score += policy.longMessageWeight;
    reasons.push("long_context");
  } else if (text.length >= policy.mediumMessageChars) {
    score += policy.mediumMessageWeight;
    reasons.push("long_context");
  }
  if (input.hasAttachments) {
    score += policy.attachmentsWeight;
    reasons.push("attachments");
  }
  if (matchesAny(policy.simpleRequestPatterns, text)) {
    score -= 35;
    reasons.push("simple_request");
  }
  let raw = chooseTier(candidates, score);
  const floorIndex = tierIndex(policy, policy.safetyFloorTierId);
  if (safetySignal && tierIndex(policy, raw.id) < floorIndex) {
    const safeCandidate = candidates.find((tier) => tierIndex(policy, tier.id) >= floorIndex);
    if (!safeCandidate) throw new Error("No allowed target satisfies the configured safety floor");
    raw = safeCandidate;
    reasons.push("safety_floor");
  }
  if (reasons.length === 0) reasons.push("balanced_default");
  if (input.mode !== "auto") {
    return finish(raw, score, raw.id, reasons);
  }
  if (!current || forceUpgrade || sameTarget(current, raw)) {
    return finish(raw, score, raw.id, reasons);
  }
  const currentIndex = tierIndex(policy, current.id);
  const rawIndex = tierIndex(policy, raw.id);
  let target = raw;
  let hysteresisApplied = false;
  if (rawIndex < currentIndex && estimatedTokens >= (policy.largeContextStickyTokens ?? Number.POSITIVE_INFINITY)) {
    target = current;
    hysteresisApplied = true;
    reasons.push("large_context_sticky");
    return finish(target, score, raw.id, reasons, hysteresisApplied);
  }
  if (rawIndex > currentIndex) {
    const required = raw.minScore + policy.switchUpMargin + penalty;
    if (score < required && !safetySignal) {
      target = current;
      hysteresisApplied = true;
      reasons.push("switch_cost_hold");
    }
  } else if (rawIndex < currentIndex) {
    const downgradeBoundary = current.minScore - policy.switchDownMargin - penalty;
    if (score >= downgradeBoundary) {
      target = current;
      hysteresisApplied = true;
      reasons.push("switch_cost_hold");
    }
  }
  return finish(target, score, raw.id, reasons, hysteresisApplied);
}

// src/capabilities.ts
var HERMES_TURN_TARGET_CAPABILITY = "composer.turn-target.v1";
var TARGET_ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$/;
var COST_CLASSES = /* @__PURE__ */ new Set(["free", "low", "standard", "premium"]);
function validateHermesCapabilities(value) {
  if (!value || typeof value !== "object") throw new Error("routing capabilities are unavailable");
  if (JSON.stringify(value).length > 65536) throw new Error("routing capability response is too large");
  const data = value;
  if (data.capability !== HERMES_TURN_TARGET_CAPABILITY || data.protocol_version !== 1) {
    throw new Error(`Hermes Gateway does not support ${HERMES_TURN_TARGET_CAPABILITY}`);
  }
  if (!COST_CLASSES.has(String(data.max_cost_class)) || typeof data.allow_cross_provider !== "boolean") {
    throw new Error("Hermes Gateway returned invalid routing policy metadata");
  }
  if (!Array.isArray(data.targets) || data.targets.length === 0 || data.targets.length > 64) {
    throw new Error("Hermes Gateway returned an invalid routing target count");
  }
  const ids = /* @__PURE__ */ new Set();
  for (const target of data.targets) {
    if (!target || typeof target.id !== "string" || !TARGET_ID.test(target.id) || ids.has(target.id) || typeof target.label !== "string" || target.label.length > 128 || !COST_CLASSES.has(String(target.cost_class)) || typeof target.enabled !== "boolean" || typeof target.requires_approval !== "boolean") {
      throw new Error("Hermes Gateway returned invalid routing targets");
    }
    ids.add(target.id);
  }
  return data;
}
var defaultSleep = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
async function requestHermesCapabilities(request, options = {}) {
  const attempts = Math.max(1, Math.min(50, options.attempts ?? 12));
  const delayMs = Math.max(0, Math.min(5e3, options.delayMs ?? 150));
  const sleep = options.sleep ?? defaultSleep;
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return validateHermesCapabilities(await request());
    } catch (error) {
      lastError = error;
      if (attempt < attempts) await sleep(delayMs);
    }
  }
  throw lastError instanceof Error ? lastError : new Error(String(lastError));
}

// integrations/hermes/desktop/plugin-entry.ts
var desktopPolicy = typeof __HERMES_TURN_ROUTER_POLICY__ === "undefined" ? codexLunaSolPolicy : __HERMES_TURN_ROUTER_POLICY__;
var PLUGIN_ID = "hermes-turn-router";
var MODES = ["auto", "save", "quality", "off"];
var $mode = atom("auto");
var $oneShotArmed = atom(false);
var $availableTargets = atom([]);
var $status = atom("Checking Gateway capability\u2026");
var $lastTarget = atom("");
var oneShot = new OneShotController();
var capabilityRefresh = null;
async function refreshCapabilities(attempts = 12) {
  if (capabilityRefresh) return capabilityRefresh;
  const task = (async () => {
    try {
      const response = await requestHermesCapabilities(
        () => host.request("router.capabilities", {}),
        { attempts, delayMs: 150 }
      );
      $availableTargets.set(
        response.targets.filter((target) => target.enabled && !target.requires_approval).map((target) => target.id)
      );
      $status.set(`${response.targets.length} targets available`);
      return true;
    } catch (error) {
      $availableTargets.set([]);
      $status.set(error instanceof Error ? error.message : String(error));
      return false;
    }
  })();
  capabilityRefresh = task;
  try {
    return await task;
  } finally {
    if (capabilityRefresh === task) capabilityRefresh = null;
  }
}
function setMode(mode) {
  $mode.set(mode);
}
function RouterControls() {
  const mode = useValue($mode);
  const oneShotArmed = useValue($oneShotArmed);
  const status = useValue($status);
  const lastTarget = useValue($lastTarget);
  const availableTargets = useValue($availableTargets);
  const gateway = useValue(host.state.gateway);
  const bestTargetId = [...desktopPolicy.tiers].reverse().find((target) => availableTargets.includes(target.id))?.id;
  return jsxs("div", {
    className: "flex items-center gap-1",
    title: status,
    children: [
      jsx(DropdownMenu, {
        children: jsxs("div", {
          children: [
            jsx(DropdownMenuTrigger, {
              asChild: true,
              children: jsxs(Button, {
                "aria-label": "Hermes Turn Router mode",
                disabled: gateway !== "open",
                size: "xs",
                type: "button",
                variant: "ghost",
                children: [
                  jsx(icons.Brain, {}),
                  `Router \xB7 ${mode}${lastTarget ? ` \u2192 ${lastTarget}` : ""}`,
                  jsx(icons.ChevronDown, {})
                ]
              })
            }),
            jsx(DropdownMenuContent, {
              align: "end",
              side: "top",
              children: MODES.map((value) => jsx(DropdownMenuItem, {
                onSelect: () => setMode(value),
                children: `${mode === value ? "\u2713 " : ""}${value}`
              }, value))
            })
          ]
        })
      }),
      jsx(Button, {
        disabled: gateway !== "open" || !bestTargetId,
        onClick: () => {
          if (!bestTargetId) return;
          if (oneShotArmed) {
            oneShot.disarm();
            $oneShotArmed.set(false);
          } else {
            oneShot.arm(bestTargetId);
            $oneShotArmed.set(true);
          }
        },
        size: "xs",
        type: "button",
        variant: oneShotArmed ? "secondary" : "ghost",
        children: oneShotArmed ? "Best \u2713" : "Best once"
      })
    ]
  });
}
var plugin = {
  id: PLUGIN_ID,
  name: "Hermes Turn Router",
  description: "Per-turn model routing with cache-aware policies and Gateway-authorized targets.",
  defaultEnabled: true,
  register(ctx) {
    const stored = ctx.storage.get("settings", { mode: "auto" });
    $mode.set(MODES.includes(stored.mode) ? stored.mode : "auto");
    const save = () => ctx.storage.set("settings", { mode: $mode.get() });
    ctx.onDispose($mode.listen(save));
    const acceptedHook = HermesSdk.onTurnAccepted;
    if (typeof acceptedHook === "function") {
      ctx.onDispose(acceptedHook((clientTurnId) => {
        if (oneShot.accepted(clientTurnId)) $oneShotArmed.set(false);
      }));
    } else {
      $status.set("Restart Hermes to activate the per-turn routing SDK");
    }
    ctx.onDispose(host.onEvent("turn.accepted", (event) => {
      const payload = event.payload;
      if (payload?.client_turn_id && oneShot.accepted(payload.client_turn_id)) {
        $oneShotArmed.set(false);
      }
    }));
    const onGateway = (state) => {
      if (state === "open") void refreshCapabilities();
    };
    ctx.onDispose(host.state.gateway.listen(onGateway));
    onGateway(host.state.gateway.get());
    ctx.registerMany([
      { id: "controls", area: COMPOSER_AREAS.actions, order: 40, render: () => jsx(RouterControls, {}) },
      {
        id: "middleware",
        area: COMPOSER_AREAS.middleware,
        order: 10,
        data: {
          async handler(draft) {
            const mode = $mode.get();
            if (mode === "off") return draft;
            const snapshot = oneShot.snapshot(draft.turnEnvelope.clientTurnId);
            let availableTargetIds = $availableTargets.get();
            if (!availableTargetIds.length) {
              await refreshCapabilities(4);
              availableTargetIds = $availableTargets.get();
            }
            if (!availableTargetIds.length) {
              oneShot.rejected(draft.turnEnvelope.clientTurnId);
              $lastTarget.set("bypass");
              host.notify({ kind: "warning", message: `Router bypassed: ${$status.get()}` });
              return draft;
            }
            const reasoningState = host.state.reasoningEffort;
            const decision = routeMessage({
              text: draft.text,
              mode,
              policy: desktopPolicy,
              allowedTargetIds: availableTargetIds,
              ...snapshot ? { oneShotTierId: snapshot.targetId } : {},
              hasAttachments: Boolean(draft.attachments?.length),
              estimatedContextTokens: host.state.focusedUsage.get()?.context_used ?? 0,
              state: {
                currentModel: host.state.model.get(),
                currentProvider: host.state.provider.get(),
                currentReasoningEffort: reasoningState?.get?.()
              }
            });
            if (!decision) return draft;
            $lastTarget.set(decision.target.label);
            $status.set(`${decision.target.label} \xB7 ${decision.reasons.join(", ")}`);
            return {
              ...draft,
              turnEnvelope: {
                ...draft.turnEnvelope,
                routingIntent: {
                  targetId: decision.target.id,
                  mode,
                  reasonCodes: [...decision.reasons]
                }
              }
            };
          }
        }
      }
    ]);
  }
};
var plugin_entry_default = plugin;
export {
  plugin_entry_default as default
};
